const REQUEST_STUDENTS_JSON = 'REQUEST_STUDENTS_JSON'
const RECEIVE_STUDENTS_JSON = 'RECEIVE_STUDENTS_JSON'
const POST_STUDENT_BEGIN = 'POST_STUDENT_BEGIN'
const POST_STUDENT_SUCCESS = 'POST_STUDENT_SUCCESS'

export default {
  REQUEST_STUDENTS_JSON,
  RECEIVE_STUDENTS_JSON,
  POST_STUDENT_BEGIN,
  POST_STUDENT_SUCCESS
}
